### ISSUE TITLE
black screen after burning

### ISSUE THREAD

**Issue by miki3421** [JohanDegraeve/M5_StickC_xdrip_iOS#1]
Hi, i tried the burner for Windows and it's seems not working. 
During the burning phase everything it's seems fine but after the Reset the device is totally dead. 
i needed to use the reset factory tool to have the device alive again.

**Comment by JohanDegraeve** [comment]
can you try again ?

**Comment by miki3421** [comment]
Hi Johan i tried again and i have the same problem. Now also i not working the burner. attached you can find some screenshot 
<img width="765" alt="error1" src="https://user-images.githubusercontent.com/42601846/72921380-6edc6300-3d4b-11ea-8ec0-a6b380bcf901.png">
<img width="780" alt="error2" src="https://user-images.githubusercontent.com/42601846/72921381-6edc6300-3d4b-11ea-85ae-c9a3efc14666.png">

**Comment by JohanDegraeve** [comment]
sorry, can you try again ?

**Comment by miki3421** [comment]
It worked !!!! 
Thanks

**Comment by JohanDegraeve** [comment]
ok
